### ISSUE TITLE
[Feature]: bump and release beta versions

### ISSUE THREAD

**Issue by mtdvlpr** [MeilCli/bump-release-action#815]
## Feature description
I want to automatically release a new beta version for every commit to the master/main branch (vXX.XX.XX-beta.X) and manuslly decide when to release the next stable version. The releases also need to contain the artifacts from another workflow which are automatically added if a draft release of the current package.json version exists.

**Comment by MeilCli** [comment]
This actions's main purpose is development custom GitHub Action.

In that case, two-tracked release is not needed.
Because we can use branch-based release/development for unstable release track.

And, multiple-tracked release will be so complicated. So, if you want multiple-track release, then I think you need making original GitHub action.
for example, a team required multiple-tracked release, the team's release-flow has some variation. main branch based development/feature branch based development/etc..
